# by default, only the health status is exposed over an unauthenticated HTTP connection.
# exposes all health check endpoints
management:
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: "*" # info,health,prometheus
    prometheus:
      enabled: true
  metrics:
    tags:
      aplicacao: ${NOME_DA_APLICACAO:Serviço de exemplo de health check}
      ambiente: ${AMBIENTE:desenvolvimento}
# CORS
      cors:
        allowed-origins: http://127.0.0.1
        allowed-methods: GET