# by default, only the health status is exposed over an unauthenticated HTTP connection.
# exposes all health check endpoints
management:
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: "*" # info,health,prometheus
    prometheus:
      enabled: true
  metrics:
    tags:
      aplicacao: ${NOME_DA_APLICACAO:Serviço de exemplo de health check}
      ambiente: ${AMBIENTE:desenvolvimento}
# CORS
      cors:
        allowed-origins: http://127.0.0.1
        allowed-methods: GET

# Jaeger - Habilita ou não
opentracing:
  jaeger:
    enabled: ${JAEGER_ENABLED:true}
    service-name: ${spring.application.name}
    # Jaeger - Endereço para enviar os metadados (trace, span, etc)
    http-sender:
      url: ${JAEGER_ENDPOINT:http://localhost:14268/api/traces}
    # Jaeger - Tipo de amostragem (probabilístico) e sua configuração (1 = 100%)
    probabilistic-sampler:
      sampling-rate: ${JAEGER_SAMPLER:1}
